- name: Add RooShop App USer
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop Application User
    
- name: Unarchive a file and extract it
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Remove Old App Content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: directory
  become_user: roboshop
  
- name: Copy {{COMPONENT}} Content
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop