- name: Setup Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}
  
- name: Install Ansible SSM Python3 Deps
  ansible.builtin.pip:
      name: "{{item}}"
      executable: pip3
  loop:
      - botocore
      - boto3