
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: "email"
    email_configs:
      - to: "learnteju14@gmail.com"      # you@example.com
        from: "learnteju14@gmail.com"  # alertmanager@example.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"  #check your amazon
        auth_username: {{ACCESSKEY}}                 #check your amazon
        auth_password: {{SECRETKEY}}                  #check your amazon
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
